server:
  port: 8080
  ssl:
    enabled: false  # 关闭
    key-store: classpath:config/https/tomcatkeystore.p12
    key-store-password: 123456

spring:
  application:
    name: sample-application
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://106.12.208.53:3306/webuy_learning?useUnicode=true&characterEncoding=UTF-8&allowMutiQueries=true&serverTimezone=Asia/Shanghai
    username: user01
    password: ak402507979
  jackson:
    property-naming-strategy: SNAKE_CASE
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 122.51.171.126
    password: ak402507979

  cloud:
    consul:
      enabled: true
      host: 127.0.0.1
      discovery:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.cloud.consul.discovery.ip-address}:${server.port}
        ip-address: 127.0.0.1
        health-check-path: /endpoint/_common/_health
        health-check-critical-timeout: 10s
        health-check-interval: 3s
  elasticsearch:
    rest:
      uris: 106.12.208.53:9200
      username: elastic
      password: ak402507979



mybatis:
  mapper-locations: classpath*:config/mybatis/mapper/**/*.xml



idempotent:
  jdbc:
    insert-sql: "INSERT INTO idempotent SET idem_key =  ? "
    update-sql: "UPDATE idempotent SET exec_result = ? WHERE idem_key = ? "
    select-sql: "SELECT exec_result FROM idempotent WHERE idem_key = ? "



rocket-mq:
  name-server: 122.51.171.126:9876
  producer:
    group: TEST_SAMPLE_01_P_GROUP
    sample-provider:
      topic: TEST_SAMPLE_01
      tag: TEST_TAG
    batch-sample-provider:
      topic: TEST_SAMPLE_BATCH_01
    batch-foreach-sample-provider:
      topic: TEST_SAMPLE_BATCH_02
  consumer:
    sample-consumer:
      trace: false
      customized-trace-topic: qaz
      topic: TEST_SAMPLE_01
      group: TEST_SAMPLE_01_C_GROUP
    batchSampleConsumer:
      trace: false
      topic: TEST_SAMPLE_BATCH_01
      group: TEST_SAMPLE_BATCH_01_C_GROUP
    batchForeachSampleConsumer:
      topic: TEST_SAMPLE_BATCH_02
      group: TEST_SAMPLE_BATCH_02_C_GROUP

compensate:
  CompensateSimpleService:
    compensate-type: METHOD_ARGS
    retry-rule: 1m 3m 1h
    alarm-rule: 10s ...
  CompensateSimpleService_2:
    compensate-type: BIZ_ID
    retry-rule: 10s 20s 30s
    alarm-rule: 30s ...
  CompensateSimpleService_3:
    compensate-type: METHOD_ARGS
    retry-rule: 10s 20s 30s
    alarm-rule: 30s ...
  CompensateSimpleService_4:
    compensate-type: METHOD_ARGS
    retry-rule: 10s 20s 30s
    alarm-rule: 30s ...

feign:
  client:
    config:
      default:
        connect-timeout: 200
        readTimeout: 3000
#      myFeignClient2:
#        connect-timeout: 2000
#        readTimeout: 5000
common:
  metric:
    influx-db:
      host: 106.12.208.53:8086
      database: java_metric
  log:
    http:
      disablePath: REQ_/hello1/**
  db:
    encrypt:
      enable: true
      password: 123456
     # password-file: E:/tmp/key/aes/aes.key
  swagger:
    basePackage: com.weweibuy.framework.samples.controller
    headers:
      - name: Authorization
        desc: token令牌
    response:
      - status: 400
        desc: 业务异常
  lb:
    server-change-listener:
      topic: COMMON_SERVER_UPDATE_TOPIC
      group: COMMON_SERVER_UPDATE_C_GROUP



