
spring:
  application:
    name: sample-application
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://106.12.208.53:3306/webuy_learning?useUnicode=true&characterEncoding=UTF-8&allowMutiQueries=true
    username: user01
    password: ak402507979
  jackson:
    property-naming-strategy: SNAKE_CASE
  redis:
    host: 122.51.171.126
    password: ak402507979



mybatis:
  mapper-locations: classpath*:config/mybatis/mapper/**/*.xml

logging:
  config: classpath:config/logback/logback-spring.xml

idempotent:
  jdbc:
    insert-sql: "INSERT INTO idempotent SET idem_key =  ? "
    update-sql: "UPDATE idempotent SET exec_result = ? WHERE idem_key = ? "
    select-sql: "SELECT exec_result FROM idempotent WHERE idem_key = ? "



rocket-mq:
  name-server: 122.51.171.126:9876
  producer:
    group: TEST_SAMPLE_01_P_GROUP
    sample-provider:
      topic: TEST_SAMPLE_01
      tag: TEST_TAG
    batch-sample-provider:
      topic: TEST_SAMPLE_BATCH_01
    batch-foreach-sample-provider:
      topic: TEST_SAMPLE_BATCH_02
  consumer:
    sample-consumer:
      trace: false
      customized-trace-topic: qaz
      topic: TEST_SAMPLE_01
      group: TEST_SAMPLE_01_C_GROUP
    batchSampleConsumer:
      trace: false
      topic: TEST_SAMPLE_BATCH_01
      group: TEST_SAMPLE_BATCH_01_C_GROUP
    batchForeachSampleConsumer:
      topic: TEST_SAMPLE_BATCH_02
      group: TEST_SAMPLE_BATCH_02_C_GROUP

compensate:
  CompensateSimpleService:
    compensate-type: METHOD_ARGS
    retry-rule: 1m 3m 1h
    alarm-rule: 10s ...
  CompensateSimpleService_2:
    compensate-type: BIZ_ID
    retry-rule: 10s 20s 30s
    alarm-rule: 30s ...
  CompensateSimpleService_3:
    compensate-type: METHOD_ARGS
    retry-rule: 10s 20s 30s
    alarm-rule: 30s ...
  CompensateSimpleService_4:
    compensate-type: METHOD_ARGS
    retry-rule: 10s 20s 30s
    alarm-rule: 30s ...

feign:
  client:
    config:
      default:
        connect-timeout: 200
        readTimeout: 3000
#      myFeignClient2:
#        connect-timeout: 2000
#        readTimeout: 5000
